#!/bin/bash
#

echo "1;CMNET-beijing"
echo "2;CMNET-tianjin"
echo "3;CMNET-hebei"
echo "4;CMNET-shangxi"
echo "5;CMNET-neimeng"
echo "6;CMNET-liaoning"
echo "7;CMNET-jilin"
echo "8;CMNET-heilongjiang"
echo "9;CMNET-shanghai"
echo "10;CMNET-jiangsu"
echo "11;CMNET-zhejiang"
echo "12;CMNET-anhui"
echo "13;CMNET-fujian"
echo "14;CMNET-jiangxi"
echo "15;CMNET-shandong"
echo "16;CMNET-henan"
echo "17;CMNET-hubei"
echo "18;CMNET-hunan"
echo "19;CMNET-guangdong"
echo "20;CMNET-guangxi"
echo "21;CMNET-hainan"
echo "22;CMNET-chongqing"
echo "23;CMNET-sichuan"
echo "24;CMNET-guizhou"
echo "25;CMNET-yunnan"
echo "26;CMNET-xizang"
echo "27;CMNET-shanxi"
echo "28;CMNET-gansu"
echo "29;CMNET-qinghai"
echo "30;CMNET-ningxia"
echo "31;CMNET-xinjiang"
echo "32;CMNET-hongkong"

